fix

diff --git a/.github/workflows/front_up_test.yml b/.github/workflows/front_up_test.yml
--- a/.github/workflows/front_up_test.yml
+++ b/.github/workflows/front_up_test.yml
@@ -11,26 +11,25 @@ jobs:
         - name: Checkout code
           uses: actions/checkout@v4
 
-        - name: Set up Python
+        - name: Install Python
           uses: actions/setup-python@v5
           with:
             python-version: '3.14' 
 
         - name: Install dependencies
-              run: |
-                python3 -m venv ./frontend-server/.venv
-                ./frontend-server/.venv/bin/pip install -r ./frontend-server/requirements.txt
+          run: |
+          python3 -m venv ./frontend-server/.venv ./frontend-server/.venv/bin/pip install -r ./frontend-server/requirements.txt
 
-            - name: Test run 
-              run: |
-                ./frontend-server/.venv/bin/python ./frontend-server/main.py &
-                PID=$!
-                sleep 5
-                if ps -p $PID > /dev/null; then
-                  echo "Success"
-                  kill $PID
-                else
-                  echo "Fail"
-                  exit 1
-              fi
+        - name: Test run 
+          run: |
+          ./frontend-server/.venv/bin/python ./frontend-server/main.py &
+          PID=$!
+          sleep 5
+          if ps -p $PID > /dev/null; then
+            echo "Success"
+            kill $PID
+          else
+            echo "Fail"
+            exit 1
+          fi   
 
