fix

diff --git a/.github/workflows/front_up_test.yml b/.github/workflows/front_up_test.yml
--- a/.github/workflows/front_up_test.yml
+++ b/.github/workflows/front_up_test.yml
@@ -7,37 +7,30 @@ on:
 jobs:
   build:
     runs-on: ubuntu-24.04
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Build the Docker image
-        run: docker compose up -d
+  steps:
+        - name: Checkout code
+          uses: actions/checkout@v4
 
+        - name: Set up Python
+          uses: actions/setup-python@v5
+          with:
+            python-version: '3.14' 
 
-steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+    - name: Install dependencies
+          run: |
+            python3 -m venv ./frontend-server/.venv
+            ./frontend-server/.venv/bin/pip install -r ./frontend-server/requirements.txt
 
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.14' 
-
-   - name: Install dependencies
-        run: |
-          python3 -m venv ./frontend-server/.venv
-          ./frontend-server/.venv/bin/pip install -r ./frontend-server/requirements.txt
-
-      - name: Test run 
-        run: |
-          ./frontend-server/.venv/bin/python ./frontend-server/main.py &
-          PID=$!
-          sleep 5
-          if ps -p $PID > /dev/null; then
-            echo "Success"
-            kill $PID
-          else
-            echo "Fail"
-            exit 1
+        - name: Test run 
+          run: |
+            ./frontend-server/.venv/bin/python ./frontend-server/main.py &
+            PID=$!
+            sleep 5
+            if ps -p $PID > /dev/null; then
+              echo "Success"
+              kill $PID
+            else
+              echo "Fail"
+              exit 1
           fi
 
