fix

diff --git a/.github/workflows/front_up_test.yml b/.github/workflows/front_up_test.yml
--- a/.github/workflows/front_up_test.yml
+++ b/.github/workflows/front_up_test.yml
@@ -16,21 +16,21 @@ jobs:
           with:
             python-version: '3.14' 
 
-    - name: Install dependencies
-          run: |
-            python3 -m venv ./frontend-server/.venv
-            ./frontend-server/.venv/bin/pip install -r ./frontend-server/requirements.txt
+        - name: Install dependencies
+              run: |
+                python3 -m venv ./frontend-server/.venv
+                ./frontend-server/.venv/bin/pip install -r ./frontend-server/requirements.txt
 
-        - name: Test run 
-          run: |
-            ./frontend-server/.venv/bin/python ./frontend-server/main.py &
-            PID=$!
-            sleep 5
-            if ps -p $PID > /dev/null; then
-              echo "Success"
-              kill $PID
-            else
-              echo "Fail"
-              exit 1
-          fi
+            - name: Test run 
+              run: |
+                ./frontend-server/.venv/bin/python ./frontend-server/main.py &
+                PID=$!
+                sleep 5
+                if ps -p $PID > /dev/null; then
+                  echo "Success"
+                  kill $PID
+                else
+                  echo "Fail"
+                  exit 1
+              fi
 
